import sys

if len(sys.argv) != 9:
    print("Usage: python3 xyz_2_lammps_data.py fileToRead fileToWrite xlo xhi ylo yhi zlo zhi")
    exit()

# Get the input and output file names from command line arguments
input_file = sys.argv[1]
output_file = sys.argv[2]

# Extract box dimensions from command line arguments
xlo, xhi, ylo, yhi, zlo, zhi = map(float, sys.argv[3:])

# Open a new file for writing
with open(output_file, 'w') as f:
    # Read the number of atoms from the input file
    with open(input_file, 'r') as f2:
        num_atoms = int(f2.readline())

    # Write the initial lines
    f.write('# Generated by /usr/workspace/wsa/lyu1/utils/xyz_2_lammsps_data.py\n')
    f.write('\n')
    f.write(f'{num_atoms} atoms\n')
    f.write('2 atom types\n')
    f.write('\n')
    f.write(f'{xlo} {xhi} xlo xhi\n')
    f.write(f'{ylo} {yhi} ylo yhi\n')
    f.write(f'{zlo} {zhi} zlo zhi\n')
    f.write('\n')
    f.write('Masses\n')
    f.write('\n')
    f.write('1  12.0107\n')
    f.write('2  14.0067\n')
    f.write('\n')
    f.write('Atoms\n')
    f.write('\n')

    # Open the input file for reading
    with open(input_file, 'r') as f2:
        # Read the lines from the file starting from line 3
        lines = f2.readlines()[2:]

        # Insert the modified lines to the output file
        for i, line in enumerate(lines, 1):
            split_line = line.split()
            if split_line[0] == "N":
                split_line[0] = "2"
            elif split_line[0] == "C":
                split_line[0] = "1"
            modified_line = f"{i} {' '.join(split_line[:4])}\n"
            f.write(modified_line)
